### PR TITLE
Fixed Travis test in Django 2.0

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by seospace** [comment]
So how do i install 2.0 compatible version? Not really clear from the issues and pull requests and 2.0 branch :))

**Comment by asfaltboy** [comment]
I've ran tests with coverage in tox (by adding this line to tox.ini:deps):

```diff
diff --git a/tox.ini b/tox.ini
index d8c4006..6eb93a1 100644
--- a/tox.ini
+++ b/tox.ini
@@ -19,6 +19,7 @@ deps =
     py{27,33,34}: pytest==2.9.1
     py{27,33,34}: pytest-django==2.9.1
     py{35,36}: pytest-django>2.9.1
+    py{27,33,34,35,36}: pytest-cov==2.5.1
     py{27,33,34,35,36}: coverage==4.1
     argparse
     django15: Django>=1.5,<1.6
```

The end results can be seen here: https://gist.github.com/ad1b8a03f5fe508431973582220879e0

Seems Django 2.0 is 95-96% covered. I went through the calls not checked and these are either unused imports (for back. compat.) or calls that are performed on other rows (i.e already tested).

I would say we can 🚢  IT !

P.s: it could be good to send coverage results to codecov.io or coveralls.io for automated checks and reporting.

**Comment by kennethlove** [comment]
Sorry this slipped my attention. I don't use `braces` much anymore so I haven't been itching for a release.

The only thing I can see to ask for would be a Tox addition for 3.6. Other than that, and maybe some packaging updates, it looks good to go.

**Comment by PetrDlouhy** [comment]
@kennethlove I added Python 3.6 to Travis (it already was in Tox). And updated the version (if it is what you mean by packagin updates) through `bumpversion` (you will probably need to run it yourself to create appropriate tag on your repository).

**Comment by kennethlove** [comment]
Thanks @PetrDlouhy! I'll do my best to get a release out this weekend.

**Comment by asfaltboy** [comment]
@kennethlove is there anything else we can do to help get this merged?

By the way, you may be interested in moving the project to https://jazzband.co/ if you don't have as large a stake in `braces` these days.

**Comment by kennethlove** [comment]
Thanks for the work you did, @PetrDlouhy! I've released 1.13 on PyPI.

And, yeah, @asfaltboy, I might move it over to Jazz Band. Mostly, though, it's just that `braces` is pretty stable and doesn't need much more than a tweak or two per release.

**Comment by michael-k** [comment]
@kennethlove Can you push tags for 1.10 to 1.13 to Github?  Thanks

**Pull request merged**
