### PR TITLE
Quick fix to ensure user is authenticated before checking time_delta

### LINKED ISSUE #176: 'AnonymousUser' object has no attribute 'last_login
When using the RecentLoginRequiredMixin, this message displays when the user is not authenticated. However, the documentation implies that the redirect for inauthenticated users should happen instead (as RecentLoginRequired is meant to include LoginRequired functionality)

### PR DESCRIPTION
**Pull request by James1345**
fixes #176

### CODE REVIEW

**Comment by kennethlove** [comment]
The `RecentLoginRequiredMixin` calls `super()` before it does the recent check. That `super()` does the `is_authenticated()` check already. I'm not sure why this change is required.

**Comment by James1345** [comment]
You are correct, this is not the right way to handle this.
The problem stems from the fact that the call to `super()` returns redirect for not logged in users, but in `RecentLoginRequiredMixin` that response is not checked to see if it is a redirect, therefore  an error occurs on the line `if now() > (request.user.last_login + delta):` as it is possible to get to this point with an anonymous user.
A better fix would be to return the response from the call to `super()` if it is a redirect response. Either way, there is a bug here that causes an unhandled error

**Comment by kennethlove** [comment]
OK, we'll look more into it soon. I want to do a point release with a couple of bug fixes in the next day or two anyway.

**Comment by kennethlove** [comment]
Another contributor submitted the `resp.status_code` check so I'm closing  this issue.

**Pull request closed without merging**
