### PR TITLE
Added a cache mixin [builds on #159]

### PR DESCRIPTION
**Pull request by adamcharnock**
Picking up on work done by @omerzimp in #159. Addressing concerns in #159 and adding tests. Last modified times must now also be timezone-aware datetimes.

Edit: Todos:
- [x] Initial documentation
- [x] Support for conditional retrieval (see the [condition mixin](https://github.com/django/django/blob/master/django/views/decorators/http.py#L69))
- [x] ~~Consider sha1'ing the response from `get_etag()`, and rename to `get_etag_data()`~~ No, a separate `ETag` class could provide better functionality, but that's probably out of scope for now.
- [x] Add support for `Cache-Control: private/public`
- [x] Finalise documentation

### CODE REVIEW

**Comment by adamcharnock** [comment]
Any thoughts on this? Yay, nay?

**Comment by kennethlove** [comment]
Sorry, @adamcharnock, we both work day jobs and have families so we don't always get a lot of time to review new PRs right away. We'll take a look at it soon and let you know if we see any problems. Thanks for submitting!

**Comment by chrisjones-brack3t** [comment]
I'm also packing for an out of state move at the moment. First thing I did notice is that there aren't any docs for this mixin.

**Comment by adamcharnock** [comment]
Absolutely no problem @kennethlove and @chrisjones-brack3t! We all have lives, I didn't mean to come across as hurrying :-)

I'll see about docs if I get a chance.

**Comment by adamcharnock** [comment]
I've just come back to this and, on second glance, I think it needs more work. I've added a list to the description, I'll get through it when I can. Any input welcome.

**Comment by adamcharnock** [comment]
Ok, I'm feeling much happier about this now. There are test cases covering covering each of the various settings and I've added some docs. This has also grown somewhat and I've considered moving it into its own ``cache`` section and out of ``other``, but I thought I'd check with you all first.

Any comments or suggestions very welcome indeed.

**Comment by dinopetrone** [comment]
what ever happened with this?

**Comment by kennethlove** [comment]
Uh, looks like some tests need to be updated?

**Comment by chrisjones-brack3t** [comment]
Closing since it's 6 years old

**Comment by adamcharnock** [comment]
Wow, I actually have no memory of ever writing this. I guess that's what 6 years does to my memory 😳

**Pull request closed without merging**
