### PR TITLE
Changed the factory call to the new api

### PR DESCRIPTION
**Pull request by ezegolub**
Tox test were failing because the factory-boy module changed it's api[1] and the basedeps pointed to the latest one available. This should make them work ok. 

[1] http://factoryboy.readthedocs.org/en/latest/changelog.html#upgrading

### CODE REVIEW

**Comment by ezegolub** [comment]
Ok, i suck at PRs. I meant to make 2 PR, each one for each of the issues: factory-boy and delete message mixin, but now both appear. I give up. Can someone point me in the right direction?

**Comment by kennethlove** [comment]
I've actually handled the FactoryBoy issue in another branch, so your changes are fine, we'll jut ignore them. Thanks for the other code. Can you tell us what it's supposed to be fixing?

**Comment by ezegolub** [comment]
I'm trying to use FormMessageMixin for the generic DeleteView, but since the form_valid() method is never called, i needed to use the delete() one to inject a message.

**Comment by kennethlove** [comment]
I'm going to merge this in but I have a feeling there's a cleaner way to achieve this. Maybe one of our contributors knows it.

Also, please provide some tests for this. I know it's pretty well covered by the existing tests, but I'd like one for this exact scenario if at all possible.

**Pull request merged**
