### PR TITLE
fix compatibility of test suit with django 1.10

### PR DESCRIPTION
**Pull request by luzfcb**
* fix compatibility of the test suit with django 1.10
* use `tox` to run test suite on travis-ci

### CODE REVIEW

**Comment by luzfcb** [comment]
@kennethlove tests fail with python3.2, because the last pip version that supports 3.2 is `7.1.2`. I have not figured out how to force `tox` use another pip version in a specific test environment

**Comment by luzfcb** [comment]
@kennethlove Python 3.2 reached the End of Life on 2016-02-20 (https://docs.python.org/devguide/#status-of-python-branches) and django officially no longer supports any version <1.8 ( https://www.djangoproject.com/download/#supported-versions)

I believe it is viable to remove support for Python 3.2 and and perhaps django <1.8

**Comment by kennethlove** [comment]
I'm OK with dropping support for Python 3.2 but earlier versions of Django are where django-braces is most useful, so I'd rather not drop support for them until/unless we have to.

**Comment by luzfcb** [comment]
@kennethlove i remove python 3.2 and all tests are now passing.
thank you for your hard work on this project.

**Comment by luzfcb** [comment]
@kennethlove ping

**Comment by luzfcb** [comment]
@kennethlove :pray: if not asking too much, could you mark this pull-request with the label "Hacktoberfest"

**Pull request merged**
