### PR TITLE
feat: remove support for python 2.7, add support for Python 3.9 & Django 3.1, 3.2

### PR DESCRIPTION
**Pull request by galuszkak**
Hi @chrisjones-brack3t @kennethlove ,

This is mostly maintenance PR. I've tried to make sure everything is passing tests. Would be really grateful for review.

Thanks

### CODE REVIEW

**Review by auvipy — APPROVED** [review]

**Comment by daveusa31** [comment]
Thanks! 
It helped me to get rid of such an exception

```
File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\advanced_filters\views.py", line 11, in <module>
    from braces.views import (CsrfExemptMixin, StaffuserRequiredMixin,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\braces\views\__init__.py", line 3, in <module>
    from ._access import (
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\braces\views\_access.py", line 13, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' 
```

**Comment by galuszkak** [comment]
Hi @kennethlove @chrisjones-brack3t , 

Kind reminder.

**Comment by galuszkak** [comment]
Hi @kennethlove @chrisjones-brack3t ,

I've updated this PR with Python 3.9 and Django 3.2 and asking very kindly for review & merge.

Please also enable back new TravisCI (they migrated from Travis-CI.org to travis-ci.com and you have to reeanble it in new domain.). 

If you need any help let me know.

**Comment by galuszkak** [comment]
Hi @kennethlove @chrisjones-brack3t ,

Kind reminder, thanks for all hard work on this project.

**Comment by kennethlove** [comment]
Sorry @galuszkak, we've both been tied up with family and work and this project is stable, so we don't check it often. I'll do my best to get your PR and others read and approved this week.

**Comment by galuszkak** [comment]
Hi @kennethlove, thanks for taking time on this. I know how much time open-source takes from private life so even more gratitude from me for looking into this.

**Comment by chrisjones-brack3t** [comment]
Starting to look at this today. 👍🏻

**Review by kennethlove — APPROVED** [review]

**Review by chrisjones-brack3t — APPROVED** [review]

**Pull request merged**
