### PR TITLE
Set the default ordering on OrderableListMixin

### PR DESCRIPTION
**Pull request by hanneshapke**
Allow a change in the default ordering for OrderableListMixin if `desc` is required as default

Pull request includes:
- ordering_default can be set, if None than `asc` is assumed
- check for correct option if option is given otherwise
  `ImproperlyConfigured` raised
- Added tests (check for the correct order if ordering_default is set
  to `asc` and `desc`, as well as test to check for ImproperlyConfigured)
- updated docs and changelog

### CODE REVIEW

**Comment by panizza** [comment]
This patch is bugged. I cloned your fork and set the ordering_default flag to "desc" and obviously the initial order is correctly set to "desc".
But after that, my queryset it will always ordered ascending even if in my queryset I explicitly set the ordering flag to "asc".
I tracked down the issue, and I found out that the problem is that whatever is the ordering value in the querystring, you always overwrite the ordering value with the default_ordering value, and because of the following statement you never assign the correct value to the ordering flag.
```python
    self.order_by = order_by
    self.ordering = self.get_ordering_default()
    if order_by and self.request.GET.get("ordering", self.ordering) == "desc":
        order_by = "-" + order_by
        self.ordering = "desc"
```
Just try by setting the default_ordering to "desc" and then by "asc".
Then change the code with the following one:
```python
    self.order_by = order_by
    self.ordering = self.get_ordering_default()
    if order_by and self.request.GET.get("ordering", self.ordering) == "desc":
        order_by = "-" + order_by
    self.ordering = self.request.GET.get("ordering", self.ordering)
```

**Comment by hanneshapke** [comment]
Hi @panizza 

Thank you for your reply and for tracking down the bug. I am testing your suggestion and will push the fix later.

-Hannes

**Comment by hanneshapke** [comment]
@panizza Added your suggestion to the PR.

**Comment by kennethlove** [comment]
Hey, can you fix the minor conflict here? I'll get this in the next release.

**Comment by hanneshapke** [comment]
Yup. Will do that this weekend.

**Pull request merged**
