### PR TITLE
add message for AccessMixin redirect to login

### PR DESCRIPTION
**Pull request by peterlauri**
I like the access mixins, but I think the login redirect can be very confusing, and can be enhanced.

### CODE REVIEW

**Comment by kennethlove** [comment]
Any updates on these docs, @peterlauri ?

**Comment by peterlauri** [comment]
I'll get right to it on Monday.

**Comment by peterlauri** [comment]
As it was quite some time ago I did this, I rebased and due to the changes in the core django-braces I could reduce the changes. I also updated the docs. @kennethlove

**Comment by kennethlove** [comment]
Looks good @peterlauri. This should make it into our next release.

**Comment by peterlauri** [comment]
I didn't add any tests though, but tests for all env except py33 are confirmed (don't have py33 on my machine)... The code changes are very minimal, and using pure django functionality with exception of the check if the message is defined... Making test for this feels overkill, but who knows, it might bite :)

**Comment by kennethlove** [comment]
Ah, completely missed that there weren't any tests.

Yes, it's a bit overkill but there should still be two tests. One for a view w/ no message set (or message explicitly set to None) that doesn't render a message. And, obviously, one with a message set so the message does show.

**Comment by peterlauri** [comment]
What do you think about the tests I just added, @kennethlove ?

**Comment by kennethlove** [comment]
You could actually use the same view class for both tests and just set the message on the view class in the "has message" test, but, yeah, those are fine.

Good job!

**Comment by peterlauri** [comment]
Thanks. When is the next release planned?

**Comment by peterlauri** [comment]
is this going to be accepted soon? I could do a rebase on the lastest changes if you want...

**Pull request closed without merging**
