### PR TITLE
Ditch PostgreSQL for testing

### PR DESCRIPTION
**Pull request by adamchainz**
Try this. I can't see any PostgreSQL specific features in the repo so I think testing without it is fine.

### CODE REVIEW

**Comment by adamchainz** [comment]
🤷‍♂ why this doesn't work

**Comment by adamchainz** [comment]
I feel like there was a regression, probably in pytest-django. I recommend pinning all requirements for testing. I have a recipe with pip-compile, see https://github.com/adamchainz/django-cors-headers/tree/master/requirements

**Comment by kennethlove** [comment]
Hey Adam! Thanks for this PR. I think Baptiste's fix is just a little cleaner so I'm gonna go with that one, but I really appreciate your time and energy on this.

**Comment by kennethlove** [comment]
(and, yes, I'm going to try and go back and drop Postgres)

**Pull request closed without merging**
